src/components/Navbar/Navbar.tsx, src/components/index.ts, src/pages/Homepage/Homepage.tsx, src/pages/Sponsors/Sponsors.tsx, src/pages/Sponsors/styles.module.css, src/pages/index.ts, src/routes/routes.tsx
added sponsors as a separate page
=> fix(sponsors): add sponsors as a separate page

.gitignore, src/components/Header/Header.tsx, src/components/Landing/Landing.tsx, src/components/Navbar/Navbar.tsx, src/components/SplideCarousel/SplideCarousel.tsx, src/pages/Auth/Login.tsx, src/pages/Auth/Register.tsx, src/pages/Auth/styles.module.css, src/pages/Auth/types.d.ts, src/pages/index.ts, src/routes/routes.tsx, yarn.lock
<ul>
<li> Added Register and Login Pages</li>
<li> Integrated Cookies and Backend with auth pages</li>
</ul>
=> feat: Add Auth Pages

index.html, src/components/Header/Header.tsx
In this PR,
- Closed Navbar Slide onClick in Mobile View
- Added Favicon
- Fixed Desktop View UI probs
=> fix(navbar): close onclick in mobile

src/components/ReCaptcha/ReCaptcha.tsx, src/components/ReCaptcha/type.d.ts, src/pages/Auth/Register.tsx, src/pages/Auth/types.d.ts
=> feat(Recaptcha): Added Recaptcha while registering

.stylelintrc, src/components/ListLayout/ListLayout.tsx, src/components/ListLayout/styles.module.css, src/components/ListLayout/types.d.ts, src/components/index.ts, src/pages/Events/Events.tsx, src/pages/Wildfire/Wildfire.tsx, src/pages/index.ts, src/routes/routes.tsx
- Added ListLayout Component
- Built Events and Wildfire on top of ListLayout
- Tried to fix stylelintrc but :(
=> Feat: Events page

src/components/AppLayout/AppLayout.tsx, src/components/Background/BackgroundAnimation.tsx, src/components/Footer/styles.module.css, src/components/Header/Header.tsx, src/components/SplideCarousel/SplideCarousel.tsx
=> fix(footer): footer ui fixes

src/components/AboutUs/AboutUs.tsx, src/components/Navbar/Navbar.tsx
In this PR,
- Added about us content
- Commented Sponsors Link from Navbar ( temporary change )
=> feat(about us): added about us content

config.example, src/pages/Auth/Register.tsx, src/pages/Auth/types.d.ts
- Update Colleges field to select and add optional other college field
=> update: colleges field to select

src/components/ListLayout/ListLayout.tsx, src/components/Navbar/Navbar.tsx, src/pages/Wildfire/Wildfire.tsx
- Add Wildfire Page
- Add PDFs
- Add Wildfire to Navbar
=> Feat: Add Wildfire Page

src/App.tsx, src/components/Header/Header.tsx, src/components/Landing/Landing.tsx, src/components/Navbar/Navbar.tsx, src/components/Navbar/styles.module.css, src/contexts/UserContext.tsx, src/pages/Auth/Login.tsx, src/pages/Auth/Register.tsx
- Switch Auth state from local storage to context
=> update: switch auth to context

src/pages/Hospitality/styles.module.css
In this PR,
- Mobile UI fix for FAQ getting cut
=> fix(hospitality): mobile ui fix

config.example, index.html, main.css, package.json, public/main.css, src/App.tsx, src/components/Navbar/Navbar.tsx, src/components/ProtectedRoute/ProtectedRoute.tsx, src/components/Toast/Toast.tsx, src/pages/Auth/Login.tsx, src/pages/EventsPage/assets/content.ts, src/pages/Hospitality/Hospitality.tsx, src/pages/Wildfire/Wildfire.tsx, src/routes/index.tsx, src/routes/protectedRoutes.tsx, src/routes/routes.tsx, vite.config.ts, yarn.lock
- Added basepath to config and configured routes and linked componenets to respect basepath
- Added toasts for redirects
=> fix: toasts, navigation basepath and routes

src/components/ProtectedRoute/ProtectedRoute.tsx, src/routes/index.tsx, src/routes/routes.tsx
=> fix: unprotected routes

src/components/Navbar/Navbar.tsx, src/pages/Workshops/Workshops.tsx
- remove localstorage userid
- fix workshop images
- add workshops to navbar
=> feat: workshop fixes

src/pages/Workshops/Workshops.tsx
- fix workshop page breaking bug
- fix workshop page image path
=> fix: workshop page

public/auth-callback.html, src/components/DAuthLogin/DAuthLogin.tsx, src/components/DAuthLogin/styles.module.css, src/components/index.ts, src/pages/Auth/Login.tsx
In this PR, 
- Added DAuth Integration
=> feat(dauth): dauth web integration

src/pages/EventsPage/assets/content.ts
- Add paper dressing event
- Change event details for Rochak Mantrana
=> Change in events page content

src/components/Header/Header.tsx, src/components/Navbar/Navbar.tsx, src/pages/Accommodation/Accommodation.tsx
- Fix Login button by updating Mobile View width
- Fix Internal scroll in Accomodation page
=> Fix: FullPage Scroll + Login Button

src/components/Header/Header.tsx, src/components/Navbar/Navbar.tsx, src/pages/Accommodation/Accommodation.tsx
Reverts delta/Festember-frontend-2022#64
=> Revert "Fix: FullPage Scroll + Login Button"

src/pages/Profile/Profile.tsx, src/pages/Profile/styleBrowser.module.css, src/pages/Profile/styleMobile.module.css
In this PR,
- Modified Profile Page to show registered events, workshops and informals
=> feat(profile): added user registered events

src/pages/Profile/Profile.tsx
In this PR,
- Added UI for having no registered events
=> fix(profile): ui for no registrated events

src/pages/Homepage/Homepage.css
Reverts delta/Festember-frontend-2022#83
=> Revert "fix(modal) : change height"

src/components/Landing/Landing.tsx
In this PR,
- Changed models to chakra models
=> fix(model): added chakra models

src/components/ListLayout/styles.module.css
In this PR,
- Changed scrolling area in events page
=> fix(events): scroll fix
